### ISSUE TITLE
processFulltextAssetDocument graphic url incorrectly including temporary (sub-)directory

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#836]
Using `processFulltextAssetDocument` we can download a zip with the XML and related image resources.

The url in the XML seem to include a temporary sub-directory,
e.g. `QwmZmbXzY9.lxml_data/image-1.png` instead of `image-1.png`

Example document `003525v1` (bioRxiv 10k training), generates the following partial TEI XML.

```xml
<figure xmlns="http://www.tei-c.org/ns/1.0" xml:id="fig_1"><head>Figure 1 :</head><label>1</label><figDesc>Figure 1: Network-based analysis of omic data to model the processes connecting genetic variation to disease.</figDesc><graphic url="QwmZmbXzY9.lxml_data/image-1.png" coords="12,72.00,178.57,319.30,504.00" type="bitmap" /></figure>
```

(The zip file doesn't contain any subdirectories)

Example command:

```bash
curl -v \
  --output "003525v1.zip" \
  --form input=@003525v1.pdf \
  https://<host>:<port>/api/processFulltextAssetDocument
```

(I have only tried that with the `cloud.science-miner.com` instance)

BTW the [FAQ](https://github.com/kermitt2/grobid/blob/a64afc8d54bcd6e1baca52603cbaad419cd3ccf2/doc/Frequently-asked-questions.md) seem to be listing the API as deprecated. Not sure if that is still correct?

**Comment by de-code** [comment]
> This is deprecated indeed (it can lead to issues when there are thousands of embedded images)

Maybe that wouldn't be as much of an issue if you only include images that you also created `graphic` elements for?
(At least that is how I have implemented it, although I do currently include an `unmatched_graphics` note section mostly for debug purpose)

**Comment by suyogricha** [comment]
Any update on this? I do not want to use pdfalto. I want to use the awesomeness of grobid only. But processFulltextAssetDocument gives incorrect temporary directory URLs and sometimes includes images in the "Pictures" directory too.

**Comment by kermitt2** [comment]
HI @suyogricha !

Thanks for feedback :) 

If I remember well, I fixed the specific problem of sub-directory in branch https://github.com/kermitt2/grobid/tree/fix-vector-graphics - however this branch introduces some very significant changes in the way figures and table are detected and structured (we will start from every graphic elements) and introduces a new figure-segmenter model, so it will take several months to have this branch merged. 

The problem of images in the zip not referenced in the TEI XML is a different problem, and it is the main purpose of this new branch, to improve the figure/table recognition. Also note that it's very common to have quite a lot of images and vector graphics not part of any figures and tables, and all the graphics won't be references anyway in the TEI XML.

**Comment by suyogricha** [comment]
Thanks a lot Patrice! Will it be possible for you to create a docker image from fix-vector-graphics branch as an alpha or beta release tag? I am sorry if I am asking too much.

**Comment by suyogricha** [comment]
I was trying to build this branch but it is giving a error while building:

(base) ➜  grobid-fix-vector-graphics ./gradlew clean install
Downloading https://services.gradle.org/distributions/gradle-7.1.1-bin.zip
..........10%...........20%...........30%..........40%...........50%...........60%..........70%...........80%...........90%...........100%

Welcome to Gradle 7.1.1!

Here are the highlights of this release:
 - Faster incremental Java compilation
 - Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :grobid-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-core:compileJava'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8m 49s
6 actionable tasks: 1 executed, 5 up-to-date
(base) ➜  grobid-fix-vector-graphics

**Comment by ayhama16** [comment]
Hi, I have tried the last version and the problem is still there.. "<graphic url="8u5Yhm3d6D.lxml_data/image-1.png" "
can you help me to fix it? Thank you so much!

**Comment by kermitt2** [comment]
Hi @suyogricha and @ayhama16 !

I've added quickly the fix to the current master with 621f5a158084e35ef7c3dd23676b98b0eb5463bf. 

```
<graphic url="image-2.png" coords="9,317.96,86.60,246.75,221.90" type="bitmap" />
```

```
$ unzip -l out.zip 
Archive:  out.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    92804  2022-02-17 05:07   tei.xml
   196898  2022-02-17 05:07   image-2.png
   112218  2022-02-17 05:07   image-1.png
---------                     -------
   401920                     3 files
```

**Comment by suyogricha** [comment]
Thanks a lot, Patrice. You are amazing. Any chances of updating this to https://hub.docker.com/r/grobid/ ?

Actually, I wish to use https://grobid.readthedocs.io/en/latest/Deep-Learning-models/ too and I am on M1 Macbook Max (Apple Silicon). It would be too complex for me to install everything.

**Comment by ayhama16** [comment]
Thanks! Can you tell me , how to build a new "grobid-core/build/libs/grobid-core-0.7.1-SNAPSHOT-onejar.jar"
because, I need it for batch commands, and I cant see it in the folder now.

Thank you !

**Comment by ayhama16** [comment]
Thanks a lot! Patrice, It works just great!

**Comment by suyogricha** [comment]
Patrice is it possible for you to update this on https://hub.docker.com/r/grobid/grobid/

**Comment by kermitt2** [comment]
@ayhama16 @suyogricha hello ! The docker images have been updated with the fix.
